# Generated by Django 6.0.3 on 2026-03-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField()),
                ('following', models.CharField()),
            ],
        ),
    ]
